### ISSUE TITLE
Importeren mislukt

### ISSUE THREAD

**Issue by bteeuwen** [openstate/program-tracker#7]
(programtracker)[bteeuwen@Ben-2 ~/dev/program-tracker]$ ./manage.py import_json
50plus.json
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_manager(settings)
  File "/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages/django/core/management/**init**.py", line 459, in execute_manager
    utility.execute()
  File "/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(_args, *_options)
  File "/Users/bteeuwen/dev/program-tracker/importdata/management/commands/import_json.py", line 28, in handle
    import_json_program(party_name, program.pk)
  File "/Users/bteeuwen/dev/program-tracker/importdata/utils.py", line 38, in import_json_program
    s = Section.objects.create(name=data['head'], program=program)
  File "/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages/django/db/models/manager.py", line 137, in create
    return self.get_query_set().create(*_kwargs)
  File "/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages/django/db/models/query.py", line 377, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/bteeuwen/dev/program-tracker/core/models.py", line 65, in save
    super(Section, self).save(_args, *_kwargs)
  File "/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages/django/db/models/base.py", line 551, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages/django/db/models/manager.py", line 203, in _insert
    return insert_query(self.model, objs, fields, *_kwargs)
  File "/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages/django/db/models/query.py", line 1576, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 910, in execute_sql
    cursor.execute(sql, params)
  File "/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 114, in execute
    return self.cursor.execute(query, args)
  File "/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/Users/bteeuwen/.virtualenvs/programtracker/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`programtracker`.`core_section`, CONSTRAINT `type_id_refs_id_3841880aab08b651` FOREIGN KEY (`type_id`) REFERENCES `core_sectiontype` (`id`))')

**Comment by breyten** [comment]
Je moet je database (de core tabellen) wel eerst leegmaken ;) (Voor core_section is dit heel lastig -- je kan het beste denk ik `./manage.py` shell doen, daarna `from core.models import Section` en dan `Section.objects.all().delete()`, waarna je core_program en core_party zou moeten kunnen leeggooien :)

**Comment by bteeuwen** [comment]
Gefixt; git pull om changes binnen te halen.

**Comment by breyten** [comment]
Ah, ja, dat wil ook helpen :D

**Comment by bteeuwen** [comment]
(just checking; die git pull loste het niet, maar hiram heeft nog wat dingen gewijzigd in de import bestanden en ik in de volgorde in de readme. die 'git pull' was meer bedoeld dat je weet dat je die weer kunt binnenhalen..)
